name: Networking

on:
  workflow_dispatch:
    inputs:
      stack:
        description: Stack
        required: true
        type: choice
        options:
          - hub
          - spoke
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  networking:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Networking
        working-directory: ./2_networking
        env:
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        run: ./main.sh "${{ inputs.stack }}" "${{ inputs.environment }}"